spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.129:3306/guli_wms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/wms/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 13000